title: Malkiz’s Dev Blog
author: Malkiz
description: Sharing thoughts and progress on my personal projects.
baseurl: ""
url: "https://malkiz.github.io"

theme: minima
timezone: Asia/Jerusalem
permalink: /:year/:month/:day/:title/

markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

sass:
  quiet_deps: true
  silence_deprecations: [import]

apps_script_url: "https://script.google.com/macros/s/AKfycbzFrcGuDmi9yFw7aRDtgP0QFTLijxH5CNQ-K7hu5_JZgBN0mdkzgsflvH0lEOArmyGo/exec"
